/*
 * Copyright Curtin University, 2015.
 */
// DO NOT MODIFY THIS FILE BY HAND. IT WAS GENERATED BY generate_orm_files.py
package au.edu.curtin.lims.db.hibernate4;

import javax.inject.Inject;

import au.edu.curtin.lims.db.IGeosampleRepository;
import au.edu.curtin.lims.domain.Geosample;

import org.hibernate.SessionFactory;

import org.springframework.stereotype.Repository;

@Repository
public class HibernateGeosampleRepository extends BaseHibernateRepository<Geosample> implements IGeosampleRepository {
    @Inject
    public HibernateGeosampleRepository(SessionFactory sessionFactory) {
        super(Geosample.class, sessionFactory);
    }

    public Geosample save(Geosample geosample) {
        this.currentSession().save(geosample);
        return geosample;
//        return new Geosample(
//            (Integer) id,
//            geosample.getMountTypeId(),
//            geosample.getIgsn(),
//            geosample.getGeosampleName(),
//            geosample.getLocation(),
//            geosample.getRockType(),
//            geosample.getSiteCode(),
//            geosample.getTectonicUnit()
//);
    }
}
