/*
 * Copyright Curtin University, 2015.
 */
// DO NOT MODIFY THIS FILE BY HAND. IT WAS GENERATED BY generate_orm_files.py
package au.edu.curtin.lims.db.hibernate4;

import javax.inject.Inject;

import au.edu.curtin.lims.db.IFactionRepository;
import au.edu.curtin.lims.domain.Faction;

import org.hibernate.SessionFactory;

import org.springframework.stereotype.Repository;

@Repository
public class HibernateFactionRepository extends BaseHibernateRepository<Faction> implements IFactionRepository {
    @Inject
    public HibernateFactionRepository(SessionFactory sessionFactory) {
        super(Faction.class, sessionFactory);
    }

    public Faction save(Faction faction) {
        this.currentSession().save(faction);
        return faction;
//        return new Faction(
//            (Integer) id,
//            faction.getFactionName()
//);
    }
}
