/*
 * Copyright Curtin University, 2015.
 */
// DO NOT MODIFY THIS FILE BY HAND. IT WAS GENERATED BY generate_orm_files.py
package au.edu.curtin.lims.db.hibernate4;

import javax.inject.Inject;

import au.edu.curtin.lims.db.IResultTypeRepository;
import au.edu.curtin.lims.domain.ResultType;

import org.hibernate.SessionFactory;

import org.springframework.stereotype.Repository;

@Repository
public class HibernateResultTypeRepository extends BaseHibernateRepository<ResultType> implements IResultTypeRepository {
    @Inject
    public HibernateResultTypeRepository(SessionFactory sessionFactory) {
        super(ResultType.class, sessionFactory);
    }

    public ResultType save(ResultType resultType) {
        this.currentSession().save(resultType);
        return resultType;
//        return new ResultType(
//            (Integer) id,
//            resultType.getResultTypeName()
//);
    }
}
