/*
 * Copyright Curtin University, 2015.
 */
// DO NOT MODIFY THIS FILE BY HAND. IT WAS GENERATED BY generate_orm_files.py
package au.edu.curtin.lims.db.hibernate4;

import javax.inject.Inject;

import au.edu.curtin.lims.db.IMineralRepository;
import au.edu.curtin.lims.domain.Mineral;

import org.hibernate.SessionFactory;

import org.springframework.stereotype.Repository;

@Repository
public class HibernateMineralRepository extends BaseHibernateRepository<Mineral> implements IMineralRepository {
    @Inject
    public HibernateMineralRepository(SessionFactory sessionFactory) {
        super(Mineral.class, sessionFactory);
    }

    public Mineral save(Mineral mineral) {
        this.currentSession().save(mineral);
        return mineral;
//        return new Mineral(
//            (Integer) id,
//            mineral.getMineralName()
//);
    }
}
