/*
 * Copyright Curtin University, 2015.
 */
// DO NOT MODIFY THIS FILE BY HAND. IT WAS GENERATED BY generate_orm_files.py
package au.edu.curtin.lims.db.hibernate4;

import javax.inject.Inject;

import au.edu.curtin.lims.db.IManufacturerRepository;
import au.edu.curtin.lims.domain.Manufacturer;

import org.hibernate.SessionFactory;

import org.springframework.stereotype.Repository;

@Repository
public class HibernateManufacturerRepository extends BaseHibernateRepository<Manufacturer> implements IManufacturerRepository {
    @Inject
    public HibernateManufacturerRepository(SessionFactory sessionFactory) {
        super(Manufacturer.class, sessionFactory);
    }

    public Manufacturer save(Manufacturer manufacturer) {
        this.currentSession().save(manufacturer);
        return manufacturer;
//        return new Manufacturer(
//            (Integer) id,
//            manufacturer.getManufacturerName()
//);
    }
}
