/*
 * Copyright Curtin University, 2015.
 */
// DO NOT MODIFY THIS FILE BY HAND. IT WAS GENERATED BY generate_orm_files.py
package au.edu.curtin.lims.db.hibernate4;

import javax.inject.Inject;

import au.edu.curtin.lims.db.IMineralMassAndColourRepository;
import au.edu.curtin.lims.domain.MineralMassAndColour;

import org.hibernate.SessionFactory;

import org.springframework.stereotype.Repository;

@Repository
public class HibernateMineralMassAndColourRepository extends BaseHibernateRepository<MineralMassAndColour> implements IMineralMassAndColourRepository {
    @Inject
    public HibernateMineralMassAndColourRepository(SessionFactory sessionFactory) {
        super(MineralMassAndColour.class, sessionFactory);
    }

    public MineralMassAndColour save(MineralMassAndColour mineralMassAndColour) {
        this.currentSession().save(mineralMassAndColour);
        return mineralMassAndColour;
//        return new MineralMassAndColour(
//            (Integer) id,
//            mineralMassAndColour.getMindifId(),
//            mineralMassAndColour.getMineralId(),
//            mineralMassAndColour.getColour(),
//            mineralMassAndColour.getMass()
//);
    }
}
