/*
 * Copyright Curtin University, 2015.
 */
// DO NOT MODIFY THIS FILE BY HAND. IT WAS GENERATED BY generate_orm_files.py
package au.edu.curtin.lims.db.hibernate4;

import javax.inject.Inject;

import au.edu.curtin.lims.db.IPersonRepository;
import au.edu.curtin.lims.domain.Person;

import org.hibernate.SessionFactory;

import org.springframework.stereotype.Repository;

@Repository
public class HibernatePersonRepository extends BaseHibernateRepository<Person> implements IPersonRepository {
    @Inject
    public HibernatePersonRepository(SessionFactory sessionFactory) {
        super(Person.class, sessionFactory);
    }

    public Person save(Person person) {
        this.currentSession().save(person);
        return person;
//        return new Person(
//            (Integer) id,
//            person.getUsername(),
//            person.getPassword(),
//            person.getEnabled()
//);
    }
}
