/*
 * Copyright Curtin University, 2015.
 */
// DO NOT MODIFY THIS FILE BY HAND. IT WAS GENERATED BY generate_orm_files.py
package au.edu.curtin.lims.db.hibernate4;

import javax.inject.Inject;

import au.edu.curtin.lims.db.IResultProcessorTypeRepository;
import au.edu.curtin.lims.domain.ResultProcessorType;

import org.hibernate.SessionFactory;

import org.springframework.stereotype.Repository;

@Repository
public class HibernateResultProcessorTypeRepository extends BaseHibernateRepository<ResultProcessorType> implements IResultProcessorTypeRepository {
    @Inject
    public HibernateResultProcessorTypeRepository(SessionFactory sessionFactory) {
        super(ResultProcessorType.class, sessionFactory);
    }

    public ResultProcessorType save(ResultProcessorType resultProcessorType) {
        this.currentSession().save(resultProcessorType);
        return resultProcessorType;
//        return new ResultProcessorType(
//            (Integer) id,
//            resultProcessorType.getResultProcessorTypeName()
//);
    }
}
