/*
 * Copyright Curtin University, 2015.
 */
// DO NOT MODIFY THIS FILE BY HAND. IT WAS GENERATED BY generate_orm_files.py
package au.edu.curtin.lims.db.hibernate4;

import javax.inject.Inject;

import au.edu.curtin.lims.db.IResultProvisionTypeRepository;
import au.edu.curtin.lims.domain.ResultProvisionType;

import org.hibernate.SessionFactory;

import org.springframework.stereotype.Repository;

@Repository
public class HibernateResultProvisionTypeRepository extends BaseHibernateRepository<ResultProvisionType> implements IResultProvisionTypeRepository {
    @Inject
    public HibernateResultProvisionTypeRepository(SessionFactory sessionFactory) {
        super(ResultProvisionType.class, sessionFactory);
    }

    public ResultProvisionType save(ResultProvisionType resultProvisionType) {
        this.currentSession().save(resultProvisionType);
        return resultProvisionType;
//        return new ResultProvisionType(
//            (Integer) id,
//            resultProvisionType.getResultProvisionTypeName()
//);
    }
}
