/*
 * Copyright Curtin University, 2015.
 */
// DO NOT MODIFY THIS FILE BY HAND. IT WAS GENERATED BY generate_orm_files.py
package au.edu.curtin.lims.db.hibernate4;

import javax.inject.Inject;

import au.edu.curtin.lims.db.IInstrumentRepository;
import au.edu.curtin.lims.domain.Instrument;

import org.hibernate.SessionFactory;

import org.springframework.stereotype.Repository;

@Repository
public class HibernateInstrumentRepository extends BaseHibernateRepository<Instrument> implements IInstrumentRepository {
    @Inject
    public HibernateInstrumentRepository(SessionFactory sessionFactory) {
        super(Instrument.class, sessionFactory);
    }

    public Instrument save(Instrument instrument) {
        this.currentSession().save(instrument);
        return instrument;
//        return new Instrument(
//            (Integer) id,
//            instrument.getManufacturerId(),
//            instrument.getInstrumentName()
//);
    }
}
