/*
 * Copyright Curtin University, 2015.
 */
// DO NOT MODIFY THIS FILE BY HAND. IT WAS GENERATED BY generate_orm_files.py
package au.edu.curtin.lims.db.hibernate4;

import javax.inject.Inject;

import au.edu.curtin.lims.db.IAuthorityRepository;
import au.edu.curtin.lims.domain.Authority;

import org.hibernate.SessionFactory;

import org.springframework.stereotype.Repository;

@Repository
public class HibernateAuthorityRepository extends BaseHibernateRepository<Authority> implements IAuthorityRepository {
    @Inject
    public HibernateAuthorityRepository(SessionFactory sessionFactory) {
        super(Authority.class, sessionFactory);
    }

    public Authority save(Authority authority) {
        this.currentSession().save(authority);
        return authority;
//        return new Authority(
//            (Integer) id,
//            authority.getAuthorityName()
//);
    }
}
