/*
 * Copyright Curtin University, 2015.
 */
// DO NOT MODIFY THIS FILE BY HAND. IT WAS GENERATED BY generate_orm_files.py
package au.edu.curtin.lims.db.hibernate4;

import javax.inject.Inject;

import au.edu.curtin.lims.db.IMountTypeRepository;
import au.edu.curtin.lims.domain.MountType;

import org.hibernate.SessionFactory;

import org.springframework.stereotype.Repository;

@Repository
public class HibernateMountTypeRepository extends BaseHibernateRepository<MountType> implements IMountTypeRepository {
    @Inject
    public HibernateMountTypeRepository(SessionFactory sessionFactory) {
        super(MountType.class, sessionFactory);
    }

    public MountType save(MountType mountType) {
        this.currentSession().save(mountType);
        return mountType;
//        return new MountType(
//            (Integer) id,
//            mountType.getMountTypeName()
//);
    }
}
