/*
 * Copyright Curtin University, 2015.
 */
// DO NOT MODIFY THIS FILE BY HAND. IT WAS GENERATED BY generate_orm_files.py
package au.edu.curtin.lims.db.hibernate4;

import javax.inject.Inject;

import au.edu.curtin.lims.db.IAnalysisRequestRepository;
import au.edu.curtin.lims.domain.AnalysisRequest;

import org.hibernate.SessionFactory;

import org.springframework.stereotype.Repository;

@Repository
public class HibernateAnalysisRequestRepository extends BaseHibernateRepository<AnalysisRequest> implements IAnalysisRequestRepository {
    @Inject
    public HibernateAnalysisRequestRepository(SessionFactory sessionFactory) {
        super(AnalysisRequest.class, sessionFactory);
    }

    public AnalysisRequest save(AnalysisRequest analysisRequest) {
        this.currentSession().save(analysisRequest);
        return analysisRequest;
//        return new AnalysisRequest(
//            (Integer) id,
//            analysisRequest.getAnalysisRequestStateId(),
//            analysisRequest.getAnalysisCapabilityId(),
//            analysisRequest.getPersonId(),
//            analysisRequest.getRequestDate()
//);
    }
}
