/*
 * Copyright Curtin University, 2015.
 */
// DO NOT MODIFY THIS FILE BY HAND. IT WAS GENERATED BY generate_orm_files.py
package au.edu.curtin.lims.db;

import au.edu.curtin.lims.domain.Faction;

public interface IFactionRepository extends IRepository<Faction> {

}
