/*
 * Copyright Curtin University, 2015.
 */
// DO NOT MODIFY THIS FILE BY HAND. IT WAS GENERATED BY generate_orm_files.py
package au.edu.curtin.lims.domain;

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

@Entity
@Table(name = "analysis_request_state")
@SequenceGenerator(name = "analysis_request_state_analysis_request_state_id_seq", sequenceName = "analysis_request_state_analysis_request_state_id_seq", allocationSize = 1)
public class AnalysisRequestState implements Comparable<AnalysisRequestState> {
    private int analysisRequestStateId;

    private String analysisRequestStateName;

    private List<AnalysisRequest> analysisRequests;

    public AnalysisRequestState() { }

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "analysis_request_state_analysis_request_state_id_seq")
    @Column(name = "analysis_request_state_id", nullable = false)
    public Integer getAnalysisRequestStateId() {
        return this.analysisRequestStateId;
    }
    
    @SuppressWarnings("unused")
    private void setAnalysisRequestStateId(Integer analysisRequestStateId) {
        this.analysisRequestStateId = analysisRequestStateId;
    }

    @Column(name = "analysis_request_state_name", nullable = false, length = 64)
    public String getAnalysisRequestStateName() {
        return this.analysisRequestStateName;
    }
    
    public void setAnalysisRequestStateName(String analysisRequestStateName) {
        this.analysisRequestStateName = analysisRequestStateName;
    }

    @OneToMany(
        mappedBy = "analysisRequestState",
        fetch = FetchType.LAZY)
    @OrderBy("analysis_request_id")
    public List<AnalysisRequest> getAnalysisRequests() {
        return this.analysisRequests;
    }
    
    public void setAnalysisRequests(List<AnalysisRequest> analysisRequests) {
        this.analysisRequests = analysisRequests;
    }

    @Override
    public int compareTo(AnalysisRequestState o) {
        return this.getAnalysisRequestStateId().compareTo(o.getAnalysisRequestStateId());
    }
}
