/*
 * Copyright Curtin University, 2015.
 */
// DO NOT MODIFY THIS FILE BY HAND. IT WAS GENERATED BY generate_orm_files.py
package au.edu.curtin.lims.domain;

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

@Entity
@Table(name = "analysis_type")
@SequenceGenerator(name = "analysis_type_analysis_type_id_seq", sequenceName = "analysis_type_analysis_type_id_seq", allocationSize = 1)
public class AnalysisType implements Comparable<AnalysisType> {
    private int analysisTypeId;

    private String analysisTypeName;

    private List<AnalysisCapability> analysisCapabilities;

    public AnalysisType() { }

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "analysis_type_analysis_type_id_seq")
    @Column(name = "analysis_type_id", nullable = false)
    public Integer getAnalysisTypeId() {
        return this.analysisTypeId;
    }
    
    @SuppressWarnings("unused")
    private void setAnalysisTypeId(Integer analysisTypeId) {
        this.analysisTypeId = analysisTypeId;
    }

    @Column(name = "analysis_type_name", nullable = false, length = 64)
    public String getAnalysisTypeName() {
        return this.analysisTypeName;
    }
    
    public void setAnalysisTypeName(String analysisTypeName) {
        this.analysisTypeName = analysisTypeName;
    }

    @OneToMany(
        mappedBy = "analysisType",
        fetch = FetchType.LAZY)
    @OrderBy("analysis_capability_id")
    public List<AnalysisCapability> getAnalysisCapabilities() {
        return this.analysisCapabilities;
    }
    
    public void setAnalysisCapabilities(List<AnalysisCapability> analysisCapabilities) {
        this.analysisCapabilities = analysisCapabilities;
    }

    @Override
    public int compareTo(AnalysisType o) {
        return this.getAnalysisTypeId().compareTo(o.getAnalysisTypeId());
    }
}
