/*
 * Copyright Curtin University, 2015.
 */
// DO NOT MODIFY THIS FILE BY HAND. IT WAS GENERATED BY generate_orm_files.py
package au.edu.curtin.lims.domain;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

@Entity
@Table(name = "authority")
@SequenceGenerator(name = "authority_authority_id_seq", sequenceName = "authority_authority_id_seq", allocationSize = 1)
public class Authority implements Comparable<Authority> {
    private int authorityId;

    private String authorityName;

    private Set<Person> people = new HashSet<Person>();

    private Set<Faction> factions = new HashSet<Faction>();

    public Authority() { }

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "authority_authority_id_seq")
    @Column(name = "authority_id", nullable = false)
    public Integer getAuthorityId() {
        return this.authorityId;
    }
    
    @SuppressWarnings("unused")
    private void setAuthorityId(Integer authorityId) {
        this.authorityId = authorityId;
    }

    @Column(name = "authority_name", nullable = false, length = 50)
    public String getAuthorityName() {
        return this.authorityName;
    }
    
    public void setAuthorityName(String authorityName) {
        this.authorityName = authorityName;
    }

    @ManyToMany(
            mappedBy = "authorities",
            fetch = FetchType.LAZY,
            cascade = { CascadeType.PERSIST, CascadeType.MERGE })
    public Set<Person> getPeople() {
        return this.people;
    }
    
    public void setPeople(Set<Person> people) {
        this.people = people;
    }

    @ManyToMany(
            mappedBy = "authorities",
            fetch = FetchType.LAZY,
            cascade = { CascadeType.PERSIST, CascadeType.MERGE })
    public Set<Faction> getFactions() {
        return this.factions;
    }
    
    public void setFactions(Set<Faction> factions) {
        this.factions = factions;
    }

    @Override
    public int compareTo(Authority o) {
        return this.getAuthorityId().compareTo(o.getAuthorityId());
    }
}
