/*
 * Copyright Curtin University, 2015.
 */
// DO NOT MODIFY THIS FILE BY HAND. IT WAS GENERATED BY generate_orm_files.py
package au.edu.curtin.lims.domain;

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

@Entity
@Table(name = "instrument")
@SequenceGenerator(name = "instrument_instrument_id_seq", sequenceName = "instrument_instrument_id_seq", allocationSize = 1)
public class Instrument implements Comparable<Instrument> {
    private int instrumentId;

    private Manufacturer manufacturer;

    private String instrumentName;

    private List<AnalysisCapability> analysisCapabilities;

    public Instrument() { }

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "instrument_instrument_id_seq")
    @Column(name = "instrument_id", nullable = false)
    public Integer getInstrumentId() {
        return this.instrumentId;
    }
    
    @SuppressWarnings("unused")
    private void setInstrumentId(Integer instrumentId) {
        this.instrumentId = instrumentId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "manufacturer_id")
    public Manufacturer getManufacturer() {
        return manufacturer;
    }
    
    public void setManufacturer(Manufacturer manufacturer) {
        this.manufacturer = manufacturer;
    }

    @Column(name = "instrument_name", nullable = false, length = 64)
    public String getInstrumentName() {
        return this.instrumentName;
    }
    
    public void setInstrumentName(String instrumentName) {
        this.instrumentName = instrumentName;
    }

    @OneToMany(
        mappedBy = "instrument",
        fetch = FetchType.LAZY)
    @OrderBy("analysis_capability_id")
    public List<AnalysisCapability> getAnalysisCapabilities() {
        return this.analysisCapabilities;
    }
    
    public void setAnalysisCapabilities(List<AnalysisCapability> analysisCapabilities) {
        this.analysisCapabilities = analysisCapabilities;
    }

    @Override
    public int compareTo(Instrument o) {
        return this.getInstrumentId().compareTo(o.getInstrumentId());
    }
}
