/*
 * Copyright Curtin University, 2015.
 */
// DO NOT MODIFY THIS FILE BY HAND. IT WAS GENERATED BY generate_orm_files.py
package au.edu.curtin.lims.domain;

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

@Entity
@Table(name = "manufacturer")
@SequenceGenerator(name = "manufacturer_manufacturer_id_seq", sequenceName = "manufacturer_manufacturer_id_seq", allocationSize = 1)
public class Manufacturer implements Comparable<Manufacturer> {
    private int manufacturerId;

    private String manufacturerName;

    private List<Instrument> instruments;

    public Manufacturer() { }

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "manufacturer_manufacturer_id_seq")
    @Column(name = "manufacturer_id", nullable = false)
    public Integer getManufacturerId() {
        return this.manufacturerId;
    }
    
    @SuppressWarnings("unused")
    private void setManufacturerId(Integer manufacturerId) {
        this.manufacturerId = manufacturerId;
    }

    @Column(name = "manufacturer_name", nullable = false, length = 64)
    public String getManufacturerName() {
        return this.manufacturerName;
    }
    
    public void setManufacturerName(String manufacturerName) {
        this.manufacturerName = manufacturerName;
    }

    @OneToMany(
        mappedBy = "manufacturer",
        fetch = FetchType.LAZY)
    @OrderBy("instrument_id")
    public List<Instrument> getInstruments() {
        return this.instruments;
    }
    
    public void setInstruments(List<Instrument> instruments) {
        this.instruments = instruments;
    }

    @Override
    public int compareTo(Manufacturer o) {
        return this.getManufacturerId().compareTo(o.getManufacturerId());
    }
}
