/*
 * Copyright Curtin University, 2015.
 */
// DO NOT MODIFY THIS FILE BY HAND. IT WAS GENERATED BY generate_orm_files.py
package au.edu.curtin.lims.domain;

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

@Entity
@Table(name = "mineral")
@SequenceGenerator(name = "mineral_mineral_id_seq", sequenceName = "mineral_mineral_id_seq", allocationSize = 1)
public class Mineral implements Comparable<Mineral> {
    private int mineralId;

    private String mineralName;

    private List<MineralOccurrence> mineralOccurrences;

    private List<MineralMassAndColour> mineralMassAndColours;

    public Mineral() { }

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "mineral_mineral_id_seq")
    @Column(name = "mineral_id", nullable = false)
    public Integer getMineralId() {
        return this.mineralId;
    }
    
    @SuppressWarnings("unused")
    private void setMineralId(Integer mineralId) {
        this.mineralId = mineralId;
    }

    @Column(name = "mineral_name", nullable = false, length = 32)
    public String getMineralName() {
        return this.mineralName;
    }
    
    public void setMineralName(String mineralName) {
        this.mineralName = mineralName;
    }

    @OneToMany(
        mappedBy = "mineral",
        fetch = FetchType.LAZY)
    @OrderBy("mineral_occurrence_id")
    public List<MineralOccurrence> getMineralOccurrences() {
        return this.mineralOccurrences;
    }
    
    public void setMineralOccurrences(List<MineralOccurrence> mineralOccurrences) {
        this.mineralOccurrences = mineralOccurrences;
    }

    @OneToMany(
        mappedBy = "mineral",
        fetch = FetchType.LAZY)
    @OrderBy("mineral_mass_and_colour_id")
    public List<MineralMassAndColour> getMineralMassAndColours() {
        return this.mineralMassAndColours;
    }
    
    public void setMineralMassAndColours(List<MineralMassAndColour> mineralMassAndColours) {
        this.mineralMassAndColours = mineralMassAndColours;
    }

    @Override
    public int compareTo(Mineral o) {
        return this.getMineralId().compareTo(o.getMineralId());
    }
}
