/*
 * Copyright Curtin University, 2015.
 */
// DO NOT MODIFY THIS FILE BY HAND. IT WAS GENERATED BY generate_orm_files.py
package au.edu.curtin.lims.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

@Entity
@Table(name = "mineral_mass_and_colour")
@SequenceGenerator(name = "mineral_mass_and_colour_mineral_mass_and_colour_id_seq", sequenceName = "mineral_mass_and_colour_mineral_mass_and_colour_id_seq", allocationSize = 1)
public class MineralMassAndColour implements Comparable<MineralMassAndColour> {
    private int mineralMassAndColourId;

    private Mindif mindif;

    private Mineral mineral;

    private int colour;

    private double mass;

    public MineralMassAndColour() { }

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "mineral_mass_and_colour_mineral_mass_and_colour_id_seq")
    @Column(name = "mineral_mass_and_colour_id", nullable = false)
    public Integer getMineralMassAndColourId() {
        return this.mineralMassAndColourId;
    }
    
    @SuppressWarnings("unused")
    private void setMineralMassAndColourId(Integer mineralMassAndColourId) {
        this.mineralMassAndColourId = mineralMassAndColourId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "mindif_id")
    public Mindif getMindif() {
        return mindif;
    }
    
    public void setMindif(Mindif mindif) {
        this.mindif = mindif;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "mineral_id")
    public Mineral getMineral() {
        return mineral;
    }
    
    public void setMineral(Mineral mineral) {
        this.mineral = mineral;
    }

    @Column(name = "colour", nullable = false)
    public int getColour() {
        return this.colour;
    }
    
    public void setColour(int colour) {
        this.colour = colour;
    }

    @Column(name = "mass", nullable = false)
    public double getMass() {
        return this.mass;
    }
    
    public void setMass(double mass) {
        this.mass = mass;
    }

    @Override
    public int compareTo(MineralMassAndColour o) {
        return this.getMineralMassAndColourId().compareTo(o.getMineralMassAndColourId());
    }
}
