/*
 * Copyright Curtin University, 2015.
 */
// DO NOT MODIFY THIS FILE BY HAND. IT WAS GENERATED BY generate_orm_files.py
package au.edu.curtin.lims.domain;

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

@Entity
@Table(name = "mount_type")
@SequenceGenerator(name = "mount_type_mount_type_id_seq", sequenceName = "mount_type_mount_type_id_seq", allocationSize = 1)
public class MountType implements Comparable<MountType> {
    private int mountTypeId;

    private String mountTypeName;

    private List<Geosample> geosamples;

    public MountType() { }

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "mount_type_mount_type_id_seq")
    @Column(name = "mount_type_id", nullable = false)
    public Integer getMountTypeId() {
        return this.mountTypeId;
    }
    
    @SuppressWarnings("unused")
    private void setMountTypeId(Integer mountTypeId) {
        this.mountTypeId = mountTypeId;
    }

    @Column(name = "mount_type_name", nullable = false, length = 64)
    public String getMountTypeName() {
        return this.mountTypeName;
    }
    
    public void setMountTypeName(String mountTypeName) {
        this.mountTypeName = mountTypeName;
    }

    @OneToMany(
        mappedBy = "mountType",
        fetch = FetchType.LAZY)
    @OrderBy("geosample_id")
    public List<Geosample> getGeosamples() {
        return this.geosamples;
    }
    
    public void setGeosamples(List<Geosample> geosamples) {
        this.geosamples = geosamples;
    }

    @Override
    public int compareTo(MountType o) {
        return this.getMountTypeId().compareTo(o.getMountTypeId());
    }
}
