/*
 * Copyright Curtin University, 2015.
 */
// DO NOT MODIFY THIS FILE BY HAND. IT WAS GENERATED BY generate_orm_files.py
package au.edu.curtin.lims.domain;

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

@Entity
@Table(name = "result_type")
@SequenceGenerator(name = "result_type_result_type_id_seq", sequenceName = "result_type_result_type_id_seq", allocationSize = 1)
public class ResultType implements Comparable<ResultType> {
    private int resultTypeId;

    private String resultTypeName;

    private List<AnalysisCapability> analysisCapabilities;

    public ResultType() { }

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "result_type_result_type_id_seq")
    @Column(name = "result_type_id", nullable = false)
    public Integer getResultTypeId() {
        return this.resultTypeId;
    }
    
    @SuppressWarnings("unused")
    private void setResultTypeId(Integer resultTypeId) {
        this.resultTypeId = resultTypeId;
    }

    @Column(name = "result_type_name", nullable = false, length = 64)
    public String getResultTypeName() {
        return this.resultTypeName;
    }
    
    public void setResultTypeName(String resultTypeName) {
        this.resultTypeName = resultTypeName;
    }

    @OneToMany(
        mappedBy = "resultType",
        fetch = FetchType.LAZY)
    @OrderBy("analysis_capability_id")
    public List<AnalysisCapability> getAnalysisCapabilities() {
        return this.analysisCapabilities;
    }
    
    public void setAnalysisCapabilities(List<AnalysisCapability> analysisCapabilities) {
        this.analysisCapabilities = analysisCapabilities;
    }

    @Override
    public int compareTo(ResultType o) {
        return this.getResultTypeId().compareTo(o.getResultTypeId());
    }
}
