/*
 * Copyright Curtin University, 2015.
 */
// DO NOT MODIFY THIS FILE BY HAND. IT WAS GENERATED BY generate_orm_files.py
package au.edu.curtin.lims.domain;

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

@Entity
@Table(name = "result_provision_type")
@SequenceGenerator(name = "result_provision_type_result_provision_type_id_seq", sequenceName = "result_provision_type_result_provision_type_id_seq", allocationSize = 1)
public class ResultProvisionType implements Comparable<ResultProvisionType> {
    private int resultProvisionTypeId;

    private String resultProvisionTypeName;

    private List<AnalysisCapability> analysisCapabilities;

    public ResultProvisionType() { }

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "result_provision_type_result_provision_type_id_seq")
    @Column(name = "result_provision_type_id", nullable = false)
    public Integer getResultProvisionTypeId() {
        return this.resultProvisionTypeId;
    }
    
    @SuppressWarnings("unused")
    private void setResultProvisionTypeId(Integer resultProvisionTypeId) {
        this.resultProvisionTypeId = resultProvisionTypeId;
    }

    @Column(name = "result_provision_type_name", nullable = false, length = 64)
    public String getResultProvisionTypeName() {
        return this.resultProvisionTypeName;
    }
    
    public void setResultProvisionTypeName(String resultProvisionTypeName) {
        this.resultProvisionTypeName = resultProvisionTypeName;
    }

    @OneToMany(
        mappedBy = "resultProvisionType",
        fetch = FetchType.LAZY)
    @OrderBy("analysis_capability_id")
    public List<AnalysisCapability> getAnalysisCapabilities() {
        return this.analysisCapabilities;
    }
    
    public void setAnalysisCapabilities(List<AnalysisCapability> analysisCapabilities) {
        this.analysisCapabilities = analysisCapabilities;
    }

    @Override
    public int compareTo(ResultProvisionType o) {
        return this.getResultProvisionTypeId().compareTo(o.getResultProvisionTypeId());
    }
}
