/*
 * Copyright Curtin University, 2015.
 */
// DO NOT MODIFY THIS FILE BY HAND. IT WAS GENERATED BY generate_orm_files.py
package au.edu.curtin.lims.domain;

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

@Entity
@Table(name = "result_processor_type")
@SequenceGenerator(name = "result_processor_type_result_processor_type_id_seq", sequenceName = "result_processor_type_result_processor_type_id_seq", allocationSize = 1)
public class ResultProcessorType implements Comparable<ResultProcessorType> {
    private int resultProcessorTypeId;

    private String resultProcessorTypeName;

    private List<AnalysisCapability> analysisCapabilities;

    public ResultProcessorType() { }

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "result_processor_type_result_processor_type_id_seq")
    @Column(name = "result_processor_type_id", nullable = false)
    public Integer getResultProcessorTypeId() {
        return this.resultProcessorTypeId;
    }
    
    @SuppressWarnings("unused")
    private void setResultProcessorTypeId(Integer resultProcessorTypeId) {
        this.resultProcessorTypeId = resultProcessorTypeId;
    }

    @Column(name = "result_processor_type_name", nullable = false, length = 64)
    public String getResultProcessorTypeName() {
        return this.resultProcessorTypeName;
    }
    
    public void setResultProcessorTypeName(String resultProcessorTypeName) {
        this.resultProcessorTypeName = resultProcessorTypeName;
    }

    @OneToMany(
        mappedBy = "resultProcessorType",
        fetch = FetchType.LAZY)
    @OrderBy("analysis_capability_id")
    public List<AnalysisCapability> getAnalysisCapabilities() {
        return this.analysisCapabilities;
    }
    
    public void setAnalysisCapabilities(List<AnalysisCapability> analysisCapabilities) {
        this.analysisCapabilities = analysisCapabilities;
    }

    @Override
    public int compareTo(ResultProcessorType o) {
        return this.getResultProcessorTypeId().compareTo(o.getResultProcessorTypeId());
    }
}
